#' Generate Party Identifiers
#'
#' Create 3-letter identifiers for parties when no party labels are supplied.
#'
#' @param x Integer: the number of parties.
#' @return A character vector of length \code{x} with deterministic 3-letter codes.
#'
#' @examples
#' if.parties.null(4)
#'
#' @export
if.parties.null <- function(x) {
  if (exists(".Random.seed", envir = .GlobalEnv)) {
    old_seed <- .Random.seed
    on.exit(assign(".Random.seed", old_seed, envir = .GlobalEnv))
  } else {
    on.exit(rm(".Random.seed", envir = .GlobalEnv))
  }
  set.seed(1)
  replicate(x, paste(sample(LETTERS, 3, replace = TRUE), collapse = ""))
}


#' Expected Vote Shares via the Taagepera-Allik Rule
#'
#' Compute the expected vote-share vector for a party system of size \code{l}
#' using the recursive Taagepera-Allik rule. The largest party's expected share
#' is \eqn{1/\sqrt{l}}; each subsequent rank takes the same fractional bite of
#' whatever mass remains:
#'
#' \deqn{\mu_1 = 1/\sqrt{l}, \qquad
#'       \mu_i = (1 - \sum_{j<i}\mu_j) / \sqrt{l - i + 1}, \quad i = 2,\dots,l.}
#'
#' The resulting vector is in descending order (largest party first) and is
#' normalised to sum to exactly 1. It is used by
#' \code{\link{sampleElectionData}} as the mean vector for the calibrated
#' Dirichlet distribution (\code{dist = "dirichlet"}).
#'
#' @param l Integer, the number of parties (\eqn{l \ge 2}).
#'
#' @return A numeric vector of length \code{l}, summing to 1, in descending
#'   order.
#'
#' @references
#' Taagepera, R. & Allik, M. (2006). Seat Share Distribution of Parties:
#' Models and Empirical Patterns. \emph{Electoral Studies}, 25(4), 696--713.
#'
#' Cohen, D. & Hanretty, C. (2024). Simulating Party Shares.
#' \emph{Political Analysis}, 32(1), 140--147.
#'
#' @examples
#' taagepera_allik(5)
#' taagepera_allik(3)
#'
#' @export
taagepera_allik <- function(l) {
  if (length(l) != 1L || !is.numeric(l) || l < 2)
    stop("'l' must be a single integer >= 2.")
  l <- as.integer(l)
  mu <- numeric(l)
  mu[1] <- 1 / sqrt(l)
  remaining <- 1 - mu[1]
  for (i in seq.int(2L, l)) {
    mu[i] <- remaining / sqrt(l - i + 1)
    remaining <- remaining - mu[i]
  }
  ## Guard against floating-point drift: normalise to sum = 1
  mu / sum(mu)
}


#' Apply Electoral Threshold at Country Level
#'
#' Zeroes out votes for parties whose nationwide vote share falls strictly
#' below the country-level threshold, before district-level apportionment.
#' A party whose share equals the threshold is retained, matching the
#' threshold convention used by \code{divisorMethods} and \code{LR_Hamilton}.
#'
#' @param np Integer: number of parties.
#' @param ne Integer: number of elections.
#' @param nd Integer: number of districts.
#' @param threshold_country Numeric: vote-share threshold in \code{[0, 1]}.
#' @param sample A list generated by \code{sampleElectionData}.
#'
#' @return The modified sample with sub-threshold party votes set to 0.
#' @keywords internal
.countryThreshold <- function(np, ne, nd, threshold_country, sample) {
  for (j in seq_len(ne)) {
    if (nd > 1L) {
      row_sums <- apply(sample[[1]][, , j], 1, sum)
    } else {
      row_sums <- sample[[1]][, , j]
    }
    total <- sum(sample[[1]][, , j])
    vote_shares <- row_sums / total

    for (i in seq_len(np)) {
      if (vote_shares[i] < threshold_country) {
        sample[[1]][i, , j] <- 0
      }
    }
  }

  sample
}


#' Compute Ideal Seat Shares
#'
#' Computes the proportional ("ideal") seat shares at country level for each
#' party in each election.
#'
#' @param ne Integer: number of elections.
#' @param nd Integer: number of districts.
#' @param np Integer: number of parties.
#' @param sample A list generated by \code{sampleElectionData}.
#'
#' @return A \code{data.frame} with columns: \code{elec}, \code{SeatTotalIdeal},
#'   \code{SeatShareIdeal}, \code{Party}.
#' @keywords internal
.seatsIdeal <- function(ne, nd, np, sample) {
  result_list <- vector("list", ne)

  for (i in seq_len(ne)) {
    total_seats <- sum(sample[[2]][[i]])
    ideal_shares <- sample[[3]][[i]]
    ideal_totals <- ideal_shares * total_seats

    result_list[[i]] <- data.frame(
      elec = paste0("e", i),
      SeatTotalIdeal = ideal_totals,
      SeatShareIdeal = ideal_shares,
      Party = as.character(if.parties.null(np)),
      stringsAsFactors = FALSE
    )
    result_list[[i]] <- result_list[[i]][order(-result_list[[i]]$SeatShareIdeal), ]
  }

  do.call(rbind, result_list)
}


#' Country-level Election Outcomes under Proportional Representation
#'
#' Allocates seats at the district level using a specified apportionment method,
#' then aggregates to country-level results.
#'
#' @param sample A list generated by \code{sampleElectionData}.
#' @param formula Character: apportionment method code (e.g., \code{"dh"},
#'   \code{"sl"}, \code{"hamilton"}).
#' @param threshold Numeric: district-level threshold in \code{[0, 1]}.
#' @param threshold_country Numeric: country-level threshold in \code{[0, 1]}.
#'
#' @return A \code{data.frame} with district-level apportionment results
#'   including columns: \code{Party}, \code{Seats}, \code{SeatShare},
#'   \code{Votes}, \code{VoteShare}, \code{id}, \code{elec}, \code{dist},
#'   \code{distTS}.
#' @keywords internal
.ProportionalRepresentation <- function(sample,
                                        formula,
                                        threshold = 0,
                                        threshold_country = 0) {
  ne <- sample$Params[1]
  nd <- sample$Params[2]
  np <- sample$Params[3]

  no_seats_dist <- unlist(sample$Seats_Dist)
  if (any(no_seats_dist == 0))
    stop("There are districts with 0 seats.")

  if (threshold_country > 0 && threshold == 0) {
    sample <- .countryThreshold(np, ne, nd, threshold_country, sample)
    dist_threshold <- 0
  } else {
    dist_threshold <- threshold
  }

  party_labels <- if.parties.null(np)
  results <- vector("list", ne * nd)
  idx <- 1L

  for (j in seq_len(ne)) {
    for (i in seq_len(nd)) {
      district_votes <- sample[[1]][, i, j]
      district_seats <- sample[[2]][[j]][i]

      if (formula == "hamilton") {
        apport <- LR_Hamilton(
          parties = party_labels,
          votes = district_votes,
          seats = district_seats,
          threshold = dist_threshold,
          order_name = TRUE
        )
      } else {
        apport <- divisorMethods(
          parties = party_labels,
          votes = district_votes,
          seats = district_seats,
          method = formula,
          threshold = dist_threshold,
          order_name = TRUE
        )
      }

      apport$id <- paste0("e", j, "d", i)
      apport$elec <- paste0("e", j)
      apport$dist <- paste0("d", i)
      apport$distTS <- sample[[2]][[j]][i]

      results[[idx]] <- apport[, c("Party", "Seats", "SeatShare", "Votes",
                                   "VoteShare", "id", "elec", "dist", "distTS")]
      idx <- idx + 1L
    }
  }

  do.call(rbind, results)
}
